name: Postman Newman CI Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm install -g newman
        npm install -g newman-reporter-slackreporter
        npm install -g newman-reporter-htmlextra

    - name: Run Postman tests
      run: newman run "GoREST Test Collection.postman_collection.json" -e "PROD.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export test-artifacts/result-report.html
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Reports
        path: test-artifacts/
        retention-days: 90

    - name: Deploy Postman Newman Report to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-artifacts